# Reusable workflow for PRs; to eject, you can replace this file with
# https://github.com/blakeinstein/blakeinstein/blob/main/.github/workflows/pr.yml
name: Pull Request

on: [pull_request]

jobs:
  build:
    uses: blakeinstein/blakeinstein/.github/workflows/pr.yml@main
